version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.3.1

# our defined job, and its steps
jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config # 動的にconfigファイルを用意する処理
          command: |
            mkdir configs
            cat \<< EOF > configs/generated_config.yml
            version: 2.1
            orbs:
              docker: circleci/docker@1.5.0
              node: circleci/node@4.2.0
            jobs:
              scan_app:
                docker:
                  - image: circleci/node:12
                steps:
                  - checkout
                  - node/install-packages:
                      override-ci-command: npm install
                      cache-path: ~/project/node_modules
            workflows:
              continue_workflow:
                jobs:
                  - scan_app
            EOF
      - continuation/continue:
          configuration_path: configs/generated_config.yml # use newly generated config to continue

# our single workflow, that triggers the setup job defined above
workflows:
  setup-workflow:
    jobs:
      - generate-config