version: 2.1


orbs:
  # import CircleCI's aws-cli orb
  aws-cli: circleci/aws-cli@3.1

jobs:
  aws-oidc:
    docker:
      - image: cimg/aws:2022.06
    steps:
      # orbsでAWS認証
      - aws-cli/assume-role-with-web-identity:
          role-arn: $AWS_ROLE_ARN # 作成した IAM ロールの ARN を環境変数から取得
      # プライベートな S3 バケットを読み取ってみる
      - run: aws s3 ls s3://circleci-oidc-example
      # パラメータストアの値を読み取ってみる
      - run: aws ssm get-parameters-by-path --path "/circleci" --recursive
      # AWS認証と接続（orbs使わない場合）
      - run:
         name: AWS認証と接続（orbs使わない場合）
         command: |
          # OpenID Connect トークンを使用して AWS 認証情報を取得
          read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
            $(aws sts assume-role-with-web-identity \
             --role-arn ${AWS_ROLE_ARN} \
             --role-session-name "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" \
             --web-identity-token $CIRCLE_OIDC_TOKEN \
             --duration-seconds 3600 \
             --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
             --output text)
          export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
          # AWS で処理を実行
          # 例) aws sts get-caller-identity

workflows:
  oidc:
    jobs:
      - aws-oidc:
          context: aws-matsunaga # 何かしら（空でも）Contextを設定しないとOIDCが使用できないので注意
