version: 2.1
jobs:
  ruby-27:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run: ruby --version
      - run: node --version

  ruby-30:
    docker:
      - image: cimg/ruby:3.0-node
    steps:
      - checkout
      - run: ruby --version
      - run: node --version

  ruby-32:
    docker:
      - image: cimg/ruby:3.2-node
    steps:
      - checkout
      - run: ruby --version
      - run: node --version

workflows:
  build:
    jobs:
      - "ruby-27"
      - "ruby-30":
          requires:
            - "ruby-27"
      - "ruby-32":
          requires:
            - "ruby-30"



