version: 2.1

orbs:
  node: circleci/node@5.1.0
  ruby: circleci/ruby@2.0.0


jobs:
  ruby-2.6.3:
    docker:
      - image: cimg/ruby:2.7-node
        environment:
          BUNDLE_JOBS: '3'
          BUNDLE_RETRY: '3'
          PGHOST: 127.0.0.1
          PGPASSWORD: ''
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: circleci-demo-ruby
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
          name: Wait for DB
      - run:
          command: bin/rails db:schema:load --trace
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
      # - run:
      #     name: Run rspec
      #     command: |
      #       bundle exec rspec --profile 10 \
      #                         --format RspecJunitFormatter \
      #                         --out test_results/rspec.xml \
      #                         --format progress \
      #                         spec/**/*_spec.rb
      # - store_test_results:
      #     path: test_results
      # - store_artifacts:
      #     path: test_results

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.6.3"





