version: 2.1
jobs:
  build:
    docker:
      # - image: cimg/ruby:2.7-node
      #   environment:
      #     BUNDLE_JOBS: '3'
      #     BUNDLE_RETRY: '3'
      #     PGHOST: 127.0.0.1
      #     PGPASSWORD: ''
      #     PGUSER: circleci-demo-ruby
      #     RAILS_ENV: test
      - image: cimg/postgres:11.18-postgis
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ''
          BUNDLE_JOBS: '3'
          BUNDLE_RETRY: '3'
          PGHOST: 127.0.0.1
          PGPASSWORD: ''
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
    steps:
      - checkout
      - run: echo "Hello CircleCI!"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m


